# Instalaccion

```
pip install pandas
```


# 01 Pandas

Numpy´s main object is the homogeneous multimencional array. It is a tabale of element (usually numbers), all of the same type, indexed by a tuple of non-negatives intergers. In NumPy dimensions are calles axes


In [1]:
import numpy as np

# 1. Array creation

- np.arry()
- np.zeros()
- np.ones()
- np.empty()
- np.eye()
- np.asarray()
- numpy.arrange()
- np.linspace()

# 1.1 np.array()

Create an array

- np.array(object,dtype=None, copy = True, order = 'K', subok=False, ndim = 0)


In [2]:
a = np.array([1, 2, 3, 4, 5, 6])  # create a one-dimensional array
print("one dimensional array: ", a)

one dimensional array:  [1 2 3 4 5 6]


array transforms sequences of sequences into two-dimencional arrays, sequences of sequences of sequences into three-dimecional arrays and so on.


In [3]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print("multidimensional array: \n", b)

multidimensional array: 
 [[1 2 3]
 [4 5 6]]


# 1.2 np.zeros(), np.one(), np.empty()

Often the elements of an array are originally unknown, but its size is known. Hence, Numpy offers several funtions to create arrays with initial placeholder content. These minimize the necesary of growing arrays, and expensive operation.

The funcion zeros creates an array full of zeros, the funcions ones creates an array full ones, and the function empty creates an array whosae initial content is random and depends on the state of the memeory. Be default, the dtype of the created array is float64. np.zeros(shape, dtype = float, order = 'C')

- np.zeros(shape, dtype = float, order = 'C')
- np.ones(shape, dtype = float, order = 'C')
- np.empty(shape, dtype = float, order = 'C')


In [4]:
c = np.zeros([2, 2])
print("array full of zeros \n", c)

array full of zeros 
 [[0. 0.]
 [0. 0.]]


In [5]:
d = np.ones([2, 2])
print("array full of ones: \n", d)

array full of ones: 
 [[1. 1.]
 [1. 1.]]


In [6]:
e = np.empty([3, 4])
print("array whose initial content is random: \n", e)

array whose initial content is random: 
 [[1.23419914e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [7.15563577e-069 8.69875793e-071 5.24244976e+174 2.04165144e+184]
 [8.02857637e-042 2.21499709e-056 1.45166083e+165 5.15455468e-062]]


# 1.3 np.eye()

Return a 2-D array with ones on the diagonal and zeros elsewhere.

- np.eye(N,M=None,K=0,dtype=float,order='C')


In [7]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# 1.4 np.asarray()

convert the input to an array

- np.asarray(a, dtype = None, order = None)


In [8]:
e = np.asarray([1, 2, 3, 4, 5, 6])
print("one-dimencional array: \n", e)

one-dimencional array: 
 [1 2 3 4 5 6]


# 1.5 the diference between array() and asarray()

The main difference is that array (by default) will make a copy of the object, while asarray will not unless necessary.


In [9]:
a = np.array([1, 2], dtype=np.float32)
print("data not changed: \n", np.array(a, dtype=np.float32) is a)
print("data changed: \n", np.array(a, dtype=np.float64) is a)
print("data not changed: \n", np.asarray(a, dtype=np.float32) is a)
print("data changed: \n ", np.asarray(a, dtype=np.float64) is a)

data not changed: 
 False
data changed: 
 False
data not changed: 
 True
data changed: 
  False


# 1.6 np.arange()

To create sequences of numbers, NumPy provides the arrange function which is analogs to the Python built-in range, but returns an array.

- numpy.arange([start, ]stop,[step, ]dtype=None)
  - start: number, optional; start of interval. The interval includes this value. The default start value is 0.
  - stop: number, end of interval. The interval. The interval does not include this value, exept in some cases where step is not an interger and floating point roud-off affects the length of out.
  - step: number,optional; Spacing between values. For any output out, this is the distance between two adjacent vales, out[i+1]-out[i]. The default step is 1. Is step is specified as a position argument, start must also be given.


In [10]:
f = np.arange(10, 20, 2)
print("sequences of numbers in array:\n", f)

sequences of numbers in array:
 [10 12 14 16 18]


# 1.7 np.linspace()

Return evenly spaced numbers over a specifiel interval

Returns num evenly spaces samples, calculated over the interval [start, stop]

The end point of the interval can optionally be excluded.

- np.linspace(start,stop,num=50, endpoint=True, rststep=False, dtype = None, axis = 0)


In [11]:
g = np.linspace(0, 99, 10)
print(g)

[ 0. 11. 22. 33. 44. 55. 66. 77. 88. 99.]


# 2. Important attributes of an ndarray object

- ndarray.ndim
  - the number of axes (dimensions) of the array
- ndarray.shape
  - the dimensions of the array. This is a tuple of intergers indicating the size of the array in each dimension. For a matrix with n rows and n columns, shape will be (n,m). The length of the shape tuple is therefore the number of the axes, ndim.
- ndarray.size
  - the totla number of element of the array. This equal to the product of the elements of shape.
- ndarray.dtype
  * an object describing the type of the element in the array. One can create or specify dtype´s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples
  *ndarray.data \* teh bugger containing the actual elements of the array. Normally, we won´t need to use this attribute because we will access the element in an array usinfg indexing facilities.


In [12]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a.shape

(3, 2)

In [13]:
a.size

6

In [14]:
a.ndim

2

In [15]:
a.dtype

dtype('int32')

# 3. Indexing, Slicing ans Iterating

ndrrays can be indexed, sliced and iterated over, much like list and other Python sequences.


In [16]:
# Indexing

a = np.array([[1, 2], [3, 4]])
b = a[0][1]
print("a:", a)
print("b:", b)

a: [[1 2]
 [3 4]]
b: 2


In [17]:
# Slicing

a = np.arange(10)
print(a[2:8:2])
print(a[2:8])
print(a[2])
print(a[2:])
print(a)

[2 4 6]
[2 3 4 5 6 7]
2
[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


# 4. Change the shape of array

Gives a new shape to an array without changing its data

- numpy.reshape(a, newshape, order = 'C')


In [18]:
a = np.arange(6)
b = a.reshape(2, 3)
print(a)
print(b)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


# 5. Broadcasting

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is 'bradcast' the larger array so taht they have compatible shapes. Broascasting provides a means of vectorizing array operatins so that looping occurs in C inteas of Python. It does this without making needless copies of data and usually leads to efficient alogorithm implemetations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of a memory that slows computation.

NumPy Operations are usuarlly done on pairs of arrays on a element-by-elemt basis. In the simplest case the two arrays must have exactly the same shape.


In [19]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
c = a * b
print(c)

[ 1  4  9 16]


When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works its way foward. Two dimensions are compatible when

- they are equal, or
- one of them is 1

If these conditions are not met, a ValueError: operands cloud not be together exception is thrown, indicating that the arrys have imcompatible shapes. The size of the resulting arrays is the size is not 1 along each axis of the inputs.

Arrsys do not need to have the same number of dimensions. For example, if yopu have a 256x256x3 array of RGB values, and you want to scale each color in the image by diferent value, you can multiply the imagen by one-dimencional array with 3 values


In [20]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 2, 3])
print(a.shape)
print(b.shape)

(3, 3)
(3,)


In [21]:
np.array([b, b, b])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [22]:
c = a + b
print("a:\n", a)
print("bradcasting:\n", c)

a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
bradcasting:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


# 6, NumPy common functions

## 6.1 ndarray.flat()

A 1-D iterator over the array.

This is a numpy.flatier instance, wich acts similarly to, but us not a subclass of, Python´s built-in iterator object.


In [23]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(a.flat[:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


## 6.2 ndarray.transpose()

Retunrs a view of the array with axes transposed.


In [24]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.transpose(a))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


## 6.3 numpy.concatenate((a1,a2...), axis=0, out=None)

join a sequence of arrays and existing axis.

- a1, a2, ... : The arrays must have same shape, except in the dimencion corresponding to axis(the first, by default)
- axis: the axis along which the arrys will be joined. If axis is None, arrays are flattened before use. Default is 0.


In [25]:
a = np.arange(6).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]


In [26]:
print(np.concatenate((a, b), axis=0))
print(np.concatenate((a, b), axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]
[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


# numpy.stack(arrays, axis = 0 , out=None)

Join a sequence of arrays along a new axis

The axis parameters specifies the index of the new axis i n the dimensions of the result. For example, if axis = 0 it will be the first dimension and if axis=-1 it will be the las dimension.


In [27]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.stack((a, b), 0)
d = np.stack((a, b), 1)

print("c:\n", c)
print("d:\n", d)

c:
 [[1 2]
 [3 4]]
d:
 [[1 3]
 [2 4]]


## 6.5 numpy.append(arr, values, axis = None)

append values to the end on an array


In [28]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.append(a, [[7, 8, 9]], axis=0)
c = np.append(a, [[7, 8, 9]])
print("b:\n", b)
print("c:\n", c)

b:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
c:
 [1 2 3 4 5 6 7 8 9]


## 6.6 numpy.insert(arr,obje,values,acis=None)

Insert values along the given axis before the given indices.


In [29]:
a = np.arange(6).reshape(2, 3)
b = np.insert(a, 2, [7, 8], axis=1)
c = np.insert(a, 2, [7, 8])
print("a=\n", a)
print("b=\n", b)
print("c=\n", c)

a=
 [[0 1 2]
 [3 4 5]]
b=
 [[0 1 7 2]
 [3 4 8 5]]
c=
 [0 1 7 8 2 3 4 5]


## 6.7 numpy.delete(arr,obj,axis=None)

Return a new values array with sub-arrays along on axis deleted. For a one dimensional array, This returns those entries not returned by arr[obj]


In [30]:
a = np.arange(6).reshape(2, 3)
b = np.delete(a, 1, axis=1)
c = np.delete(a, 1)
print("a=\n", a)
print("b=\n", b)
print("c=\n", c)

a=
 [[0 1 2]
 [3 4 5]]
b=
 [[0 2]
 [3 5]]
c=
 [0 2 3 4 5]


# 7. Matrix

This module contains all functions in the numpy namescape, with the following replacement functions that return matrices instead of ndarrys.

- empty(shape[,dtype,order])
  - Return a new matrix of given shape and type, without initializing entries.
- zeros(shape[,dtype,order])
  - Return a matrix of given shape ansd type, filled with zeros.
- ones(shape[,dtype,order])
  - Matrix of ones
- eye(n[,M,k,dtype,order])
  - Return a matrix with ones on the diagonal and zeros elsewhere
- indentity(n[,dtype])
  - returns the square identity matrix of given size
- repmat(a,m,n)
  - Return a 0-D to 2-D array or matrix MxN times.
- rand(\*args)
  - return a matrix of random values with given shape.
- randn(\*args)
  - Return a random matrix with data from the "standard normal" distribution.


In [31]:
import numpy.matlib

## 7.1 Create a matrix by np.matlib.zeros() and np.matlib.ones()


In [32]:
a = np.matlib.zeros((2, 2))
b = np.matlib.ones((2, 2))
print("a=\n", a)
print("b=\n", b)

a=
 [[0. 0.]
 [0. 0.]]
b=
 [[1. 1.]
 [1. 1.]]


## 7.2 creat a diagonal matrix by np.matlib.eye()


In [33]:
c = np.matlib.eye(3)
print("c =\n", c)

c =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 7.3 Transfer between array and matrix


In [34]:
# transfer an array to a matrix

d = np.array([[1, 2], [3, 4]])
d = np.mat(d)
print(d)
print(type(d))

# transfer a matrix to an array

a = np.mat([[1, 2, 3], [4, 5, 6]])
b = a.getA()
print("matrix a=\n", a)
print(type(a))
print("array b=\n", b)
print(type(b))

[[1 2]
 [3 4]]
<class 'numpy.matrix'>
matrix a=
 [[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>
array b=
 [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## 7.4 randomly create a matrix by np.matlibh.rand()


In [35]:
a = np.matlib.rand(3, 3)
print("a=\n", a)

a=
 [[0.49912909 0.65609584 0.68097353]
 [0.90010016 0.66474578 0.75511843]
 [0.62607392 0.55474016 0.50368843]]


## 7.7 matrix operations

matrix.dot(b, out=None)/numpy.dot(a,b,out=None)

Dot product of two arrays

Dot product of two arrays. Specifically.

- If both a and b are 1-D arrays, it is inner product of vectors (withoujt complex conjugation)
- if both a and b are 2-D arrsys, it is a matrix multiplication, but using matmul or a @ b is prefered
- if both a and b are 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a,b) or a \* b
- If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.
- If s is an N-D and b is an M-D array (where M>=2), it is a sum product over the las axis of a and the second-to-last axis of b:
  - dot(a,b)[i,k,l] = sum(a[i,j...]\*b[k,l...])


In [36]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[1, 1], [2, 2]])
print(np.dot(a, b))  # matrix multiplication
print(a @ b)  # matrix multiplication

[[1 1]
 [2 2]]
[[1 1]
 [2 2]]


multiply


In [37]:
print(np.multiply(a, b))  # equivalent to multiply
print(a * b)  # equivalent to multiply

[[1 0]
 [0 2]]
[[1 0]
 [0 2]]


## 7.8 Matrix Inverse

In [39]:
a = np.matrix([[2, 0, 0], [0, 1, 0], [0, 0, 2]])
b = a.I
print("matrix a:\n", a)
print("matrix b:\n", b)

matrix a:
 [[2 0 0]
 [0 1 0]
 [0 0 2]]
matrix b:
 [[0.5 0.  0. ]
 [0.  1.  0. ]
 [0.  0.  0.5]]


## 7.9 Determinant of a matrix

In [40]:
a = np.matrix([[1, 2], [3, 4]])
b = np.linalg.det(a)
print("a:\n", a)
print("b:\n", b)

a:
 [[1 2]
 [3 4]]
b:
 -2.0000000000000004


## 7.10 sum, max, min

In [43]:
a = np.matrix([[1, 2], [3, 4]])
b = a.sum(axis=0) # sum by columns
c = a.sum(axis=1) #sum by raws
print("matrix a:\n", a)
print("b:\n", b)
print("c:\n", c)

matrix a:
 [[1 2]
 [3 4]]
b:
 [[4 6]]
c:
 [[3]
 [7]]


In [44]:
d = a.max()
e = a.min()
print("d:\n", d)
print("e:\n", e)

d:
 4
e:
 1


# 8.Random sampling

## 8.1 simple random data

* rand(d0,d1,...,dn)Random vales([0.0,1.0]) in a given shape.
* randn(d0,d1,...,dn) Return a sample (or samples) from the 'standard normal' distribution
* randint(low[,higg,size,dtype]) Return random intergers from low (inclusive) to high (exclusive).

In [45]:
r1 = np.random.rand(2, 2)
r2 = np.random.randn(2, 2)
r3 = np.random.randint(0, 5)
print("r1:\n", r1)
print("r2:\n", r2)
print("r3:\n", r3)

r1:
 [[0.96764394 0.08355547]
 [0.94794564 0.39661932]]
r2:
 [[ 0.46278383 -0.02732649]
 [-0.24855702 -0.11701941]]
r3:
 1


* numpy.random.choise(a,size=None,repalce=True,p=None)
    * a: if an ndarray, a random smaple is generated from its elements. If an int, the random sample is generated as if was np.arange(n)
    * size: output shape.
    * replace: boolean,optional; whether the sample is with each entry in a. If not give the sample assumes a uniform distribution over all entries in a.

In [47]:
r3 = np.random.choice([1, 2, 3, 4, 5], (2, 2), p=[0.1, 0, 0.3, 0.6, 0])
print(r3)

[[4 4]
 [4 4]]


## 8.2 Permutations

*   shuffle(x) modify a sequence in-place by shuffing uts contents
*   permutation(x) randomly permute a sequence, or return a permuted range

In [51]:
a = np.array([1, 2, 3, 4, 5])
np.random.shuffle(a)
print("a:\n", a)
b = np.random.permutation([1, 2, 3, 4, 5])

print("a:\n", a)
print("b:\n", b)

a:
 [2 1 5 3 4]
a:
 [2 1 5 3 4]
b:
 [2 4 5 1 3]


## 8.3 distributions

*   normal([loc,scale,size]) Draw random samples forma a normal (Gaussian) distribution.
    *   loc:Mean('centre') of the distribution
    *   scale:Standard deviation (spread or 'width') of the distribution
    *   size: Ouput shape.
*   uniform([low,high,size]) Draw samples forma a uniform distribution
    *   samples are uniformly distributed over the half-open interval [low,high] (includes low, but excludes high). in other words, any value within the given is equally likely to be drawn by uniform.
    *   low: lowe boundary of the output interval.All values generated will be greater that or equal to low. The default value is 0-
    *   high: Upper boundary of the output interval. All values generated will be less tha high. The default value is 1.0
    *   size: output shape
* poisson([lam,size]) draw samples form a poisson distribution
    *   lam: expectation of interval, should be >=0.A sequense of expectation intervals must be broadcastable over the requested size.
    *   size: output shape

In [52]:
r1 = np.random.normal(0, 0.1, 5)
r2 = np.random.uniform(0, 5, 2)
r3 = np.random.poisson(5, 2)

print("r1:\n", r1)
print("r2:\n", r2)
print("r3:\n", r3)

r1:
 [-0.07052912 -0.05060692 -0.06204586 -0.16049166 -0.00926326]
r2:
 [3.414098   4.11340071]
r3:
 [7 1]


# 9. Comon mathematical functions

## 9.1 Trigonometric funcitons

*   sin(x,/[out,where,casting,order,....]) trigonomtric sice,elemet-wise
*   cos(x,/[out,where,casting,order...]) cosine elemen-wise

In [54]:
a = np.array([0, 30, 45, 60, 90])
b = np.sin(a * np.pi / 180)
c = np.cos(a * np.pi / 180)
print("b:\n", b)
print("c:\n", c)

b:
 [0.         0.5        0.70710678 0.8660254  1.        ]
c:
 [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


## 9.2 Rounding

*   around(a[,decimals,out]) Evenly round to the given number of decimal
*   flor(x,/[,out,where,casting,order...]) Return the floor of the input, element-wise
*   ceil(x,/[out,where,casting,order,...]) Return the ceiling of the input, element-wise

In [55]:
a = np.array([1.0, 1.5, 2.0, 2.55])
b = np.around(a)
c = np.around(a, decimals=1)
print("b:\n", b)
print("c:\n", c)

b:
 [1. 2. 2. 3.]
c:
 [1.  1.5 2.  2.6]


## 9.3 arithmetic operations


In [56]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
c = np.add(a, b)
d = np.subtract(a, b)
e = np.multiply(a, b)
f = np.divide(a, b)
g = np.mod(a, b)
h = np.power(a, b)
print("c:\n", c)
print("d:\n", d)
print("e:\n", e)
print("f:\n", f)
print("g:\n", g)
print("h:\n", h)

c:
 [5 5 5 5]
d:
 [-3 -1  1  3]
e:
 [4 6 6 4]
f:
 [0.25       0.66666667 1.5        4.        ]
g:
 [1 2 1 0]
h:
 [1 8 9 4]


## 9.4 Statical function

*   numpy.amin(a,axis=None,out=None,keepdims=,initial=)
    *   Return the minimum of an array or minumum along on axis.
*   numpy.amax(a,axis=None,out=None,keepdims=,initial=)
    *   Return the maximun of an array or maximum along axis
*   numpy.median(a,axis=None,out=None,over_write_input=False,Keepdims=False)
    * Compute the median along the specified axis.Returns the median of the array elements.
*   numpy.mean(a,axis=None,dtype=None,out=None,keepdims=)
    *   Compute the arithmetic mean along the specified axis.

In [57]:
a = np.array([[6, 7, 2], [0, 1, 5]])
b = np.amin(a,0)
c = np.amax(a,1)
d = np.median(a)
e = np.mean(a)
print("a:\n", a)
print("b:\n", b)
print("c:\n", c)
print("d:\n", d)
print("e:\n", e)

a:
 [[6 7 2]
 [0 1 5]]
b:
 [0 1 2]
c:
 [7 5]
d:
 3.5
e:
 3.5


## 9.5 Sort funtion
*   numpy.sort(a,axis=-1,kind='quicksort',order=None)

Return a sorted copy an array

In [58]:
a = np.array([[3, 5, 1], [2, 8, 7]])
b = np.sort(a)
c = np.sort(a, axis=0)
print(b)
print(c)

[[1 3 5]
 [2 7 8]]
[[2 5 1]
 [3 8 7]]
